name: Pull Request CI

on:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Run tests
        run: forge test -vvvv

      - name: Generate coverage report
        run: forge coverage --report lcov

      - name: Filter coverage report
        run: |
          sudo apt update
          sudo apt -y install lcov
          lcov --remove ./lcov.info 'lib/*' 'script/*' 'test/*' -o ./lcov.info.pruned
      
      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./lcov.info.pruned
          github-token: ${{ secrets.GITHUB_TOKEN }}

  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Check contract sizes
        run: forge build --sizes

      - name: Check gas snapshots
        run: forge snapshot --check