name: Pull Request CI

on:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvvv

      - name: Generate coverage report
        run: forge coverage --report lcov

      - name: Filter coverage report
        run: |
          sudo apt update
          sudo apt -y install lcov
          lcov --remove ./lcov.info -o ./lcov.info.pruned 'lib' 'script' 'test'
      
      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./lcov.info.pruned
          github-token: ${{ secrets.GITHUB_TOKEN }}
