name: Pull Request CI

on:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Pull Request Test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvvv

      - name: Generate coverage report
        run: forge coverage --report lcov
      
      - uses: danielealbano/lcov-action@v1
        with:
          output_lcov_info: coverage.info
          remove_patterns: test,script,lib

      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
